---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# R Cheatsheet

## Load libraries
```R
if (!require(testthat)) install.packages('testthat')
library(testthat)
```

## Self learning
```R
library("swirl")
```

## Vectors

```{r vectors}
rep(c(0, 1, 2), each = 10)

rep(c(0, 1, 2), times = 10)
```

## Memory management

```{r memory}
# Sample dataset of 1000 rows
some_df <- data.frame(rep(1:100, 10),
                             rep(101:200, 10),
                             rep(201:300, 10))

object.size(some_df) # Reports the memory size allocated to the object

rm("some_df") # Removes only the object itself and not necessarily the memory allotted to it
gc() # Force R to release memory it is no longer using
ls() # Lists all the objects in your current workspace

rm(list = ls()) # If you want to delete all the objects in the workspace and start with a clean slate
```

## Apply functions

```
# https://purrr.tidyverse.org/reference/map.html
library(dplyr)
myList <- mtcars[1:20,] %>%
  split(.$cyl) %>%
  map(~ lm(mpg ~ wt, data = .x)) %>%
  map_dfr(~ as.data.frame(t(as.matrix(coef(.)))))
```

## testthat

### Prepare package

```
install.packages("testthat")

usethis::create_package("myPackageName")
usethis::use_test("myPackageName") # creates tests/testthat/test-mypackage.R
usethis::use_description(
  fields = list(Package = "myPackageName"),
  check_name = TRUE,
  roxygen = TRUE
)

usethis::use_package("zip", min_version = "1.0.0") # adds "Imports: zip (>= 1.0.0)" to DESCRiPTION file
```

### Run tests

```
library(testthat)
test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})
```

### Run test coverage

```
library(covr)
devtools::load_all(".")
covr <- file_coverage("R/fahrenheit_to_celsius.R", "tests/testthat/test-myPackageName.R")
covr
report(covr)
```

### Automate project setup

```
library(usethis)

# Create a new package -------------------------------------------------
path <- file.path(tempdir(), "mypkg")
create_package(path)

proj_activate(path)

# Modify the description ----------------------------------------------
use_mit_license("My Name")

use_package("ggplot2", "Suggests")

# Set up other files -------------------------------------------------
use_readme_md()

use_news_md()

use_test("my-test")

x <- 1
y <- 2
use_data(x, y)

# Use git ------------------------------------------------------------
use_git()

# Call function multiple times ------------------------------------------------------------
lapply(format_vec, function(f)
  write_dataset(
    dataset = mtcars,
    path = output_folder,
    format = f
  ))

write_dataset_preset <- function(f) {
  write_dataset(
    dataset = mtcars,
    path = output_folder,
    format = f
  )
}
lapply(format_vec, write_dataset_preset)
purrr::walk(format_vec, write_dataset_preset)
```
